### ISSUE TITLE
serch&discoveryパラメータ付きコレクションで価格を非表示にする

### ISSUE THREAD

**Issue by takakura-sh** [StoreHero-StoreFront/.github#1]
## Overview
serch&discoveryでのフィルタが適用されたパラメータ付きコレクション表示で、商品サムネイル下部に表示される価格を非表示にする

## Purpose
ダブル・クイーンなどの各商品で共通しているサイズのバリアントでまとめたコレクションで、その商品バリアント表示にリンクしているのだが、サイズによって価格が大きくかわる。
ただ、コレクションではデフォルトの一番小さいサイズの価格が表示されてしまうため、この矛盾を解決する目的

## Requirement specification
?filter.v.option.サイズ=　というパラメータがつくコレクション表示では、一覧での価格を非表示にする

以下は対象のページ（5サイズ分）
ちなみに、今後新たなサイズ展開（いまはないキングサイズなど）が追加されても上記のパラメータであれば非表示になるとありがたいです。

- https://iwonu.jp/collections/semi-single?filter.v.option.%E3%82%B5%E3%82%A4%E3%82%BA=%E3%82%BB%E3%83%9F%E3%82%B7%E3%83%B3%E3%82%B0%E3%83%AB
- https://iwonu.jp/collections/single?filter.v.option.%E3%82%B5%E3%82%A4%E3%82%BA=%E3%82%B7%E3%83%B3%E3%82%B0%E3%83%AB
- https://iwonu.jp/collections/semi-double?filter.v.option.%E3%82%B5%E3%82%A4%E3%82%BA=%E3%82%BB%E3%83%9F%E3%83%80%E3%83%96%E3%83%AB
- https://iwonu.jp/collections/double?filter.v.option.%E3%82%B5%E3%82%A4%E3%82%BA=%E3%83%80%E3%83%96%E3%83%AB
- https://iwonu.jp/collections/queen?filter.v.option.%E3%82%B5%E3%82%A4%E3%82%BA=%E3%82%AF%E3%82%A4%E3%83%BC%E3%83%B3

## Due date
2/5くらいまでにできるとありがたいです

**Comment by sakashin** [comment]
@takakura-sh 
では、こちら対応しました。

デモURL：パラメータあるとき
https://3uvg89097zslghhz-56195776679.shopifypreview.com/collections/semi-single?filter.v.option.%E3%82%B5%E3%82%A4%E3%82%BA=%E3%82%BB%E3%83%9F%E3%82%B7%E3%83%B3%E3%82%B0%E3%83%AB

パラメータないとき
https://3uvg89097zslghhz-56195776679.shopifypreview.com/collections/semi-single

**Comment by takakura-sh** [comment]
@sakashin ご対応ありがとうございます。確認しました。こちらで問題ないので、いけるときに実装をお願いしたいです！

**Comment by takakura-sh** [comment]
@sakashin こちらですが、もうしばらくかかりそうですか？ご予定だけお聞きしたく。

**Comment by sakashin** [comment]
@takakura-sh 
おお、すいません！
てっきり確認していただいているものと思ってました。こちらはいつでもいけます。

**Comment by takakura-sh** [comment]
@sakashin ありがとうございます！では本番反映お願いできますか？

**Comment by sakashin** [comment]
記入場所が違っていたのでクローズ

**Comment by sakashin** [comment]
こちらに移設
https://github.com/StoreHero-StoreFront/shopify-iwonu/issues/15
